spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: P@ssw0rd
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB




